name: AzureUpdates to Hugo Importer
description: Grabs current azure service updates rss feed and converts it to json to be used in HUGO
branding:
  icon: archive
  color: orange
inputs:
  filename:
    description: Filename of the convert jsonfile within the data folder
    required: false
    type: string
    default: azureupdatesfeed.json
  rawfilename:
    description: Filename of the downloaded xmlfile within the data folder
    required: false
    type: string
    default: azureupdatesfeed.xml
runs:
  using: docker
  image: Dockerfile